spring.application.name=hospitalManagementSystem

server.port=8081

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalDb

spring.datasource.username=postgres
spring.datasource.password=93489

# This will create schema on running your application and will also drop all schemas once you stop your application
spring.jpa.hibernate.ddl-auto=update

# TO see all the sql statements runned by hibernate
spring.jpa.show-sql=true

#Format the hibernate queries, statements
spring.jpa.properties.hibernate.format_sql=true


#spring.jpa.defer-datasource-initialization=true
# spring.sql.init.mode=always
# spring.sql.init.data-locations=classpath:data.sql